//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfa_casScolaireDepart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_resultat
    {
        public string no_cours { get; set; }
        public string no_da { get; set; }
        public string session_ { get; set; }
        public Nullable<short> note { get; set; }
    
        public virtual tbl_cours tbl_cours { get; set; }
        public virtual tbl_etudiant tbl_etudiant { get; set; }
    }
}
